package com.sdgwarriors.healthygrove.ui.theme

import androidx.compose.ui.graphics.Color

val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)

val light_primary =               Color(0xFF006e00)
val light_onPrimary =             Color(0xFFffffff)
val light_primaryContainer =      Color(0xFF73ff5a)
val light_onPrimaryContainer =    Color(0xFF002200)
val light_secondary =             Color(0xFF625B71)
val light_onSecondary =           Color(0xFFFFFFFF)
val light_secondaryContainer =    Color(0xFFE8DEF8)
val light_onSecondaryContainer =  Color(0xFF1D192B)
val light_tertiary =              Color(0xFF7D5260)
val light_onTertiary =            Color(0xFFFFFFFF)
val light_tertiaryContainer =     Color(0xFFFFD8E4)
val light_onTertiaryContainer =   Color(0xFF31111D)
val light_error =                 Color(0xFFB3261E)
val light_errorContainer =        Color(0xFFF9DEDC)
val light_onError =               Color(0xFFFFFFFF)
val light_onErrorContainer =      Color(0xFF410E0B)
val light_background =            Color(0xFFfbfdfd)
val light_onBackground =          Color(0xFF191c1d)
val light_surface =               Color(0xFFfbfdfd)
val light_onSurface =             Color(0xFF191c1d)
val light_surfaceVariant =        Color(0xFFE7E0EC)
val light_onSurfaceVariant =      Color(0xFF49454F)
val light_outline =               Color(0xFF79747E)
val light_inverseOnSurface =      Color(0xFFeff1f1)
val light_inverseSurface =        Color(0xFF2d3132)
val light_inversePrimary =        Color(0xFF00e600)
val light_shadow = Color(0xFF000000)

val dark_primary =                Color(0xFF00e600)
val dark_onPrimary =              Color(0xFF003a00)
val dark_primaryContainer =       Color(0xFF005300)
val dark_onPrimaryContainer =     Color(0xFF73ff5a)
val dark_secondary =              Color(0xFFCCC2DC)
val dark_onSecondary =            Color(0xFF332D41)
val dark_secondaryContainer =     Color(0xFF4A4458)
val dark_onSecondaryContainer =   Color(0xFFE8DEF8)
val dark_tertiary =               Color(0xFFEFB8C8)
val dark_onTertiary =             Color(0xFF492532)
val dark_tertiaryContainer =      Color(0xFF633B48)
val dark_onTertiaryContainer =    Color(0xFFFFD8E4)
val dark_error =                  Color(0xFFF2B8B5)
val dark_errorContainer =         Color(0xFF8C1D18)
val dark_onError =                Color(0xFF601410)
val dark_onErrorContainer =       Color(0xFFF9DEDC)
val dark_background =             Color(0xFF191c1d)
val dark_onBackground =           Color(0xFFe0e3e3)
val dark_surface =                Color(0xFF191c1d)
val dark_onSurface =              Color(0xFFe0e3e3)
val dark_surfaceVariant =         Color(0xFF49454F)
val dark_onSurfaceVariant =       Color(0xFFCAC4D0)
val dark_outline =                Color(0xFF938F99)
val dark_inverseOnSurface =       Color(0xFF191c1d)
val dark_inverseSurface =         Color(0xFFe0e3e3)
val dark_inversePrimary =         Color(0xFF006e00)
val dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)